Repository AFNetworking/AFNetworking, pull requests merged in 2019-10, with the labels that each got.

#4201 Update code coverage settings
  .codecov.yml
  fastlane/.env.macos
  fastlane/.env.osx_10.11_xcode7
  fastlane/.env.tvos9_xcode7
Labels: continuous integration, project config, tests

#4014 Adding tvOS User Agent
  AFNetworking/AFURLRequestSerialization.m
Labels: needs tests

#3912 Fix wrong delegate method in `AFURLSessionManager` annotation
  AFNetworking/AFURLSessionManager.h
Labels: needs backmerge/rebase
