Repository AFNetworking/AFNetworking, pull requests merged in 2020-03, with the labels that each got.

#4406 Fix `NetworkActivityIndicator` kvo call back will trigger twice bug.
  Tests/Tests/AFNetworkActivityManagerTests.m
  UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m
Labels: needs review

#4401 Delete unused `af_url_session_manager_creation_queue ` when don’t support below iOS 8
  AFNetworking/AFURLSessionManager.m
  Tests/Tests/AFURLSessionManagerTests.m
Labels: needs review

#4007 Change dataTaskWithHTTPMethod visibility to public
  AFNetworking/AFHTTPSessionManager.h
Labels: needs feedback

#4407 Optimizing cancel image download and let task to be canceled really.
  Tests/Tests/AFImageDownloaderTests.m
  UIKit+AFNetworking/AFImageDownloader.m
Labels: needs review

#3425 Pinning failure better error
  AFNetworking/AFURLSessionManager.h
  AFNetworking/AFURLSessionManager.m
  Tests/Tests/AFHTTPSessionManagerTests.m
Labels: needs review, security

#4393 Post a notification when finishing moving the downloaded file successfully.
  AFNetworking/AFURLSessionManager.h
  AFNetworking/AFURLSessionManager.m
  Tests/Tests/AFURLSessionManagerTests.m
Labels: needs tests
