Repository AFNetworking/AFNetworking, pull requests merged in 2020-01, with the labels that each got.

#4196 Fixed memory leak issues
  AFNetworking/AFURLSessionManager.m
  Example/Today Extension Example/TodayViewController.m
  Example/macOS Example/AppDelegate.m
Labels: needs feedback

#3752 Search for default pinned certificates in the main bundle
  AFNetworking/AFSecurityPolicy.h
  AFNetworking/AFSecurityPolicy.m
Labels: needs review, security

#3872 fix AssociatedObject bug
  UIKit+AFNetworking/UIButton+AFNetworking.m
  UIKit+AFNetworking/UIImageView+AFNetworking.m
Labels: needs review
